config/routes.rb
Rails.application.routes.draw do
  resources :video_galleries
  resources :contacts
  resources :photo_galleries
  resources :articles
  resources :events
  devise_for :users

  resources :articles do
    resources :comments
  end
  root "articles#index"
  get "pages/contacts" => 'pages#contacts'
  get "pages/about_us" => 'pages#about_us'
    
  get 'persons/profile', as: 'user_root'

end

app/models/article.rb
require 'carrierwave/orm/activerecord'

class Article < ActiveRecord::Base

 mount_uploader :poster, PictureUploader
 
 has_many :comments, dependent: :destroy
 validates :title, presence: true, length: { minimum: 5 }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base





end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/photo_gallery.rb
class PhotoGallery < ActiveRecord::Base

validates :name, presence: true
mount_uploaders :pictures, PictureUploader
serialize :pictures, JSON

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video_gallery.rb
class VideoGallery < ActiveRecord::Base
    attr_accessor 'videos_file_name'
    has_attached_file :attachment,
         :processors => lambda { |a| a.is_video? ? [ :ffmpeg ] : [ :thumbnail ] }
        validates_attachment_content_type :attachment, content_type: /\Avideo\/.*\Z/ 
    #mount_uploader :videos, VideoUploader 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_filter :authenticate_user!, :except => [:show, :index]

def index
    @articles = Article.all
  end

def show
    @article = Article.find(params[:id])
end

def new
    @article = Article.new
end
 
def create
  @article = Article.new(article_params)
  @article.poster = params[:article][:poster]

  if @article.save
    redirect_to @article
  else
    render 'new'
  end
end

def edit
  @article = Article.find(params[:id])
end

def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end

def destroy
  @article = Article.find(params[:id])
  @article.destroy
 
  redirect_to articles_path
end

private
  def article_params
    params.require(:article).permit(:title, :body, :poster)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_filter :authenticate_user!, :except => [:show, :index]

 def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_filter :authenticate_user!, :except => [:show, :index]

def index
    @events = Event.all
  end

def show
    @event = Event.find(params[:id])
end

def new
    @event = Event.new
end
 
def create
  @event = Event.new(event_params)
  if @event.save
    redirect_to @event
  else
    render 'new'
  end
end

def edit
  @event = Event.find(params[:id])
end

def update
  @event = Event.find(params[:id])
 
  if @event.update(event_params)
    redirect_to @event
  else
    render 'edit'
  end
end

def destroy
  @event = Event.find(params[:id])
  @event.destroy
 
  redirect_to events_path
end

private
  def event_params
    params.require(:event).permit(:name, :description, :location, :location_frame, :start_time, :finish_time)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController    

before_filter :authenticate_user!, :except => [:show, :index]


def about_us
end

def contacts
end

private
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
    

  def profile
    @profile = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/photo_galleries_helper.rb
module PhotoGalleriesHelper
end

app/helpers/photo_gallery_helper.rb
module PhotoGalleryHelper
end

app/helpers/video_galleries_helper.rb
module VideoGalleriesHelper
end

app/views/articles/_form.html.haml
= form_for @article, html: { class: "form form-horizontal article" } do |f|
  .form-group
    = f.label :title, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :title, class: 'form-control', required: true
    = f.error_span(:title)
  .form-group
    = f.label :body, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :body, class: 'form-control', required: true
    = f.error_span(:body)
  .form-group
    = f.label :poster, class: 'control-label col-lg-2'
    .col-lg-10
      = f.file_field :poster, class: "file_field", required: true
    = f.error_span(:poster)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), articles_path, :class => 'btn btn-default'

app/views/articles/edit.html.haml
- model_class = Article
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/articles/index.html.haml
- model_class = Article
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:body)
      %th= model_class.human_attribute_name(:poster)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @articles.each do |article|
      %tr
        %td= article.id
        %td= link_to article.title, article_path(article)
        %td= article.body
        %td= image_tag article.poster.url, class: "img-rounded", height: "80"
        %td=l article.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_article_path(article), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), article_path(article), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_article_path, :class => 'btn btn-primary'

app/views/articles/new.html.haml
- model_class = Article
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/articles/show.html.haml
- model_class = Article
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @article.title
%p
  %strong= model_class.human_attribute_name(:body) + ':'
  %br
  = @article.body
%p
  %strong= model_class.human_attribute_name(:poster) + ':'
  %br
  = image_tag @article.poster.url, height: "300px"


= link_to t('.back', :default => t("helpers.links.back")), articles_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_article_path(@article), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), article_path(@article), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/comments/_comment.html.haml
%div{style: "border-bottom: 1px solid gray; width: 300px; "}
  %p
    %strong Commenter:
    = comment.commenter 
    
  %p
    %strong Comment:
    = comment.body 

  %p
    = link_to 'Destroy Comment', [comment.article, comment],
                   method: :delete,
                   data: { confirm: 'Are you sure?' } 

app/views/comments/_form.html.haml
= form_for([@article, @article.comments.build]) do |f| 
  %p
    = f.label :commenter 
    %br
    = f.text_field :commenter 
  %p
    = f.label :body 
    %br
    = f.text_area :body 
  
  %p
    = f.submit 

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :start_time
    = f.datetime_select :start_time
  .field
    = f.label :finish_time
    = f.datetime_select :finish_time
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :location_frame
    = f.text_area :location_frame
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
- model_class = Event
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/events/index.html.haml
- model_class = Event
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:start_time)
      %th= model_class.human_attribute_name(:finish_time)
      %th= model_class.human_attribute_name(:location)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @events.each do |event|
      %tr
        %td= event.id
        %td= link_to event.name, event_path(event)
        %td= event.description
        %td= event.start_time.strftime("at %I:%M%p")
        %td= event.finish_time.strftime("at %I:%M%p")
        %td= event.location
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_event_path(event), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), event_path(event), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_event_path, :class => 'btn btn-primary'

app/views/events/new.html.haml
- model_class = Event
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/events/show.html.haml
- model_class = Event
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @event.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @event.description
%p
  %strong= model_class.human_attribute_name(:start_time) + ':'
  %br
  = @event.start_time
%p
  %strong= model_class.human_attribute_name(:finish_time) + ':'
  %br
  = @event.finish_time
%p
  %strong= model_class.human_attribute_name(:location) + ':'
  %br
  = @event.location
%p
  %strong= model_class.human_attribute_name(:location_frame) + ':'
  %br
  = @event.location_frame.html_safe



= link_to t('.back', :default => t("helpers.links.back")), events_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_event_path(@event), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), event_path(@event), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'