config/routes.rb
Rails.application.routes.draw do
  resources :video_galleries
  resources :contacts
  resources :photo_galleries
  resources :articles
  resources :events
  devise_for :users

  resources :articles do
    resources :comments
  end
  root "articles#index"
  get "pages/contacts" => 'pages#contacts'
  get "pages/about_us" => 'pages#about_us'
    
  get 'persons/profile', as: 'user_root'

end

app/models/article.rb
require 'carrierwave/orm/activerecord'

class Article < ActiveRecord::Base

 mount_uploader :poster, PictureUploader
 
 has_many :comments, dependent: :destroy
 validates :title, presence: true, length: { minimum: 5 }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base





end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/photo_gallery.rb
class PhotoGallery < ActiveRecord::Base

validates :name, presence: true
mount_uploaders :pictures, PictureUploader
serialize :pictures, JSON

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video_gallery.rb
class VideoGallery < ActiveRecord::Base
    attr_accessor 'videos_file_name'
    has_attached_file :attachment,
         :processors => lambda { |a| a.is_video? ? [ :ffmpeg ] : [ :thumbnail ] }
        validates_attachment_content_type :attachment, content_type: /\Avideo\/.*\Z/ 
    #mount_uploader :videos, VideoUploader 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_filter :authenticate_user!, :except => [:show, :index]

def index
    @articles = Article.all
  end

def show
    @article = Article.find(params[:id])
end

def new
    @article = Article.new
end
 
def create
  @article = Article.new(article_params)
  @article.poster = params[:article][:poster]

  if @article.save
    redirect_to @article
  else
    render 'new'
  end
end

def edit
  @article = Article.find(params[:id])
end

def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end

def destroy
  @article = Article.find(params[:id])
  @article.destroy
 
  redirect_to articles_path
end

private
  def article_params
    params.require(:article).permit(:title, :body, :poster)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_filter :authenticate_user!, :except => [:show, :index]

 def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_filter :authenticate_user!, :except => [:show, :index]

def index
    @events = Event.all
  end

def show
    @event = Event.find(params[:id])
end

def new
    @event = Event.new
end
 
def create
  @event = Event.new(event_params)
  if @event.save
    redirect_to @event
  else
    render 'new'
  end
end

def edit
  @event = Event.find(params[:id])
end

def update
  @event = Event.find(params[:id])
 
  if @event.update(event_params)
    redirect_to @event
  else
    render 'edit'
  end
end

def destroy
  @event = Event.find(params[:id])
  @event.destroy
 
  redirect_to events_path
end

private
  def event_params
    params.require(:event).permit(:name, :description, :location, :location_frame, :start_time, :finish_time)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController    

before_filter :authenticate_user!, :except => [:show, :index]


def about_us
end

def contacts
end

private
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
    

  def profile
    @profile = current_user
  end

end

app/controllers/photo_galleries_controller.rb
class PhotoGalleriesController < ApplicationController

  before_filter :authenticate_user!, :except => [:show, :index]


def index
    @photo_galleries = PhotoGallery.paginate(:page => params[:page], :per_page => 3)
  end

def show
    @photo_gallery = PhotoGallery.find(params[:id])
end

def new
    @photo_gallery = PhotoGallery.new
end
 
def create
  @photo_gallery = PhotoGallery.new(photo_gallery_params)
  #@photo_gallery.pictures = params[:photo_gallery][:pictures]

  if @photo_gallery.save
    redirect_to @photo_gallery
  else
    render 'new'
  end
end

def edit
  @photo_gallery = PhotoGallery.find(params[:id])
end

def update
  @photo_gallery = PhotoGallery.find(params[:id])
 
  if @photo_gallery.update(photo_gallery_params)
    redirect_to @photo_gallery
  else
    render 'edit'
  end
end

def destroy
  @photo_gallery = PhotoGallery.find(params[:id])
  @photo_gallery.destroy
 
  redirect_to photo_galleries_path
end




private
def photo_gallery_params
  params.require(:photo_gallery).permit(:name, :describtion, pictures: [])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/photo_galleries_helper.rb
module PhotoGalleriesHelper
end

app/helpers/photo_gallery_helper.rb
module PhotoGalleryHelper
end

app/helpers/video_galleries_helper.rb
module VideoGalleriesHelper
end

app/views/photo_galleries/_form.html.haml
= form_for @photo_gallery, html: { class: "form form-horizontal photo_gallery" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control', required: true
    = f.error_span(:name)
  .form-group
    = f.label :describtion, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :describtion, class: 'form-control', required: true
    = f.error_span(:describtion)
  .form-group
    = f.label :pictures, class: 'control-label col-lg-2'
    .col-lg-10
      = f.file_field :pictures, multiple: true, class: 'form-control', required: true
    = f.error_span(:pictures)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), photo_galleries_path, :class => 'btn btn-default'

app/views/photo_galleries/edit.html.haml
- model_class = PhotoGallery
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/photo_galleries/index.html.haml
- model_class = PhotoGallery
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:describtion)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @photo_galleries.each do |photo_gallery|
      %tr
        %td= link_to photo_gallery.id, photo_gallery_path(photo_gallery)
        %td= link_to photo_gallery.name, photo_gallery_path(photo_gallery)
        %td= photo_gallery.describtion
        %td=l photo_gallery.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_photo_gallery_path(photo_gallery), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), photo_gallery_path(photo_gallery), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= will_paginate @photo_galleries
= link_to t('.new', :default => t("helpers.links.new")), new_photo_gallery_path, :class => 'btn btn-primary'

app/views/photo_galleries/new.html.haml
- model_class = PhotoGallery
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/photo_galleries/show.html.haml
- model_class = PhotoGallery
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @photo_gallery.name
%p
  %strong= model_class.human_attribute_name(:describtion) + ':'
  %br
  = @photo_gallery.describtion
%p
  %strong= model_class.human_attribute_name(:pictures) + ':'
  %br
  - @photo_gallery.pictures.each do |p|
    = image_tag p.url, class: "img-rounded", width: "140px"


= link_to t('.back', :default => t("helpers.links.back")), photo_galleries_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_photo_gallery_path(@photo_gallery), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), photo_gallery_path(@photo_gallery), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'