config/routes.rb
Rails.application.routes.draw do
  resources :video_galleries
  resources :contacts
  resources :photo_galleries
  resources :articles
  resources :events
  devise_for :users

  resources :articles do
    resources :comments
  end
  root "articles#index"
  get "pages/contacts" => 'pages#contacts'
  get "pages/about_us" => 'pages#about_us'
    
  get 'persons/profile', as: 'user_root'

end

app/models/article.rb
require 'carrierwave/orm/activerecord'

class Article < ActiveRecord::Base

 mount_uploader :poster, PictureUploader
 
 has_many :comments, dependent: :destroy
 validates :title, presence: true, length: { minimum: 5 }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base





end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/photo_gallery.rb
class PhotoGallery < ActiveRecord::Base

validates :name, presence: true
mount_uploaders :pictures, PictureUploader
serialize :pictures, JSON

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video_gallery.rb
class VideoGallery < ActiveRecord::Base
    attr_accessor 'videos_file_name'
    has_attached_file :attachment,
         :processors => lambda { |a| a.is_video? ? [ :ffmpeg ] : [ :thumbnail ] }
        validates_attachment_content_type :attachment, content_type: /\Avideo\/.*\Z/ 
    #mount_uploader :videos, VideoUploader 
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_filter :authenticate_user!, :except => [:show, :index]

def index
    @events = Event.all
  end

def show
    @event = Event.find(params[:id])
end

def new
    @event = Event.new
end
 
def create
  @event = Event.new(event_params)
  if @event.save
    redirect_to @event
  else
    render 'new'
  end
end

def edit
  @event = Event.find(params[:id])
end

def update
  @event = Event.find(params[:id])
 
  if @event.update(event_params)
    redirect_to @event
  else
    render 'edit'
  end
end

def destroy
  @event = Event.find(params[:id])
  @event.destroy
 
  redirect_to events_path
end

private
  def event_params
    params.require(:event).permit(:name, :description, :location, :location_frame, :start_time, :finish_time)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController    

before_filter :authenticate_user!, :except => [:show, :index]


def about_us
end

def contacts
end

private
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
    

  def profile
    @profile = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/photo_galleries_helper.rb
module PhotoGalleriesHelper
end

app/helpers/photo_gallery_helper.rb
module PhotoGalleryHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebPortal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'swfobject' %>
  <%= csrf_meta_tags %>
  <style>
  body {
background: url('http://hires.photospublic.com/PP31131112-Extreme-light-blue-sky.jpg') no-repeat center center;
background-size: "100%";}
  </style> 
</head>
<body>
  <div class="container">
    <%= nav_bar fixed: :top, brand: "Dnepr Acro Family" do %>
        <%= menu_group do %>
            <%= menu_item "Статьи", articles_path %>
            <%= menu_item "Фото", photo_galleries_path %>
            <%= menu_item "Видео", video_galleries_path %>
            <%= menu_item "События", events_path %>
            <%= menu_item "О нас", '/pages/about_us'%>
            <%= menu_item "Контакты", '/pages/contacts'%>
        <% end %>
        <% if current_user %>
          <%= menu_group do %>
            <%= menu_item "Выход", destroy_user_session_path, :method => :delete  %>
          <%end%>
        <% else %>
            <%= menu_group pull: :right do %>
                <%= menu_item "Авторизация", new_user_session_path %>
                <%= menu_item "Регистрация", new_user_registration_path %>
            <% end %>
      <% end %>
    <% end %>
    <div class="container">
      <div class="row">
        <div class="span9">
          <%= yield %>  
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/pages/about_us.html.haml
%div{class: "row"}
  %div{class: "col-sm-6 col-md-4"}
    %div{class: "thumbnail"}
      %img{src: "https://pp.userapi.com/c633226/v633226661/36d23/WNQVm8k5JYA.jpg", alt: "", height: "150px"}
      %div{class: "caption"}
        %h3 Танюха Круговая
        %p Наша зажигалка. Что бы ни происходило в нашей семье - она всегда в центре внимания
        %a{href: "https://www.facebook.com/profile.php?id=100013971647405&fref=pb&hc_location=friends_tab&pnref=friends.all", class: "btn btn-primary", role: "button"} Перейти
%div{class: "row"}
  %div{class: "col-sm-6 col-md-4"}
    %div{class: "thumbnail"}
      %img{src: "https://pp.userapi.com/c841039/v841039350/6098/S0XlTuJqJ3k.jpg", alt: "", height: "150px"}
      %div{class: "caption"}
        %h3 Макс Булгаков
        %p Креативный директор всея мероприятий. Будь-то погром в собственном доме или уютная обстановка в зале, он придумает что с этим сделать
        %a{href: "https://www.facebook.com/max.bulgakov.73", class: "btn btn-primary", role: "button"} Перейти
%div{class: "row"}
  %div{class: "col-sm-6 col-md-4"}
    %div{class: "thumbnail"}
      %img{src: "https://pp.userapi.com/c626326/v626326816/34258/nrR4WWgTyes.jpg", alt: "", height: "150px"}
      %div{class: "caption"}
        %h3 Екатерина Донгаузер
        %p Наш уже учитель акройоги и самая важная часть семьи, без которой уже невозможно жить.
        %a{href: "https://vk.com/kat_von_di", class: "btn btn-primary", role: "button"} Перейти

app/views/pages/contacts.html.haml
%h1 Наши контакты
%h3 FaceBook:
%a{href: "https://www.facebook.com/groups/338000513259785/?fref=ts"} Dnepr Acro Family
%h3 Vk:
%a{href: "https://vk.com/acroyoga_lab"} Art acro labs
%h1 Нас можно найти: Сквер Ленина (внизу улицы Кирова)
%div{class: "row", style: "width: 650px;"}
  %div
    %a{href: "#", class: "thumbnail"}
      %iframe{src:"https://www.google.com/maps/d/embed?mid=1nmPRDQMzNvFgl53CuUURzkeg6fI&hl=ru", width:"640", height:"480"}

app/views/user_root/user_root.html.haml
- if user_signed_in? 
    %span Hello, = current_user.email 
    = link_to 'Exit', destroy_user_session_path, :method => :delete 
- else 
    = link_to 'Log_in', new_user_session_path 
    = link_to 'Sign_in', new_user_registration_path 